services:
  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile

    container_name: investing_api

    ports:
      - "5000:8080"

    environment:
      - ConnectionStrings__Default=Server=host.docker.internal;Database=master;User Id=fscsia;Password=csfais;TrustServerCertificate=True
      - Brapi__Token=chyuDjzoytFDSTbk8SbEYY

    extra_hosts:
      - "host.docker.internal:host-gateway"